apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.pvName }}
spec:
  capacity:
    storage: {{ .Values.mysql.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mysql.storageClass }}
  hostPath:
    path: {{ .Values.mysql.hostPath }}
